global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']
  - job_name: 'ai-detector'
    static_configs:
      - targets: ['ai-detector:5001']
