apiVersion: apps/v1
kind: Deployment
metadata:
  name: pq-tls-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pq-tls-simulator
  template:
    metadata:
      labels:
        app: pq-tls-simulator
    spec:
      containers:
      - name: simulator
        image: pq-tls-simulator:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pq-tls-simulator
spec:
  selector:
    app: pq-tls-simulator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
