version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
  core:
    build: ./core
  demo_app:
    build: ./demo_app
  attacks:
    build: ./attacks
  blockchain:
    build: ./blockchain
  ai-detector:
    build: ./ai-detector
  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
